export enum Situation {
  EXPECTANT_NEW_BABY = 'EXPECTANT_NEW_BABY',
  PARENT = 'PARENT',
  PARENT_AND_EXPECTANT_NEW_BABY = 'PARENT_AND_EXPECTANT_NEW_BABY',
}
export enum privilege {
  SUPERADMIN = 'SUPERADMIN',
  SCIENTIST = 'SCIENTIST',
  MEMEBER = 'MEMBER',
}
export enum level {
  EASY = 'EASY',
  MODERATE = 'MODERATE',
  WITH_EFFORT = 'WITH_EFFORT',
}
export enum rating {
  NORMAL = 'NORMAL',
  NICE = 'NICE',
  VERY_GREAT = 'VERY_GREAT',
}
